# Generated by Django 3.2.3 on 2021-05-21 21:46

import Api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_start_date', models.DateTimeField()),
                ('crop_harvest_date', models.DateTimeField()),
                ('is_harvested', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(default='', max_length=50)),
                ('farm_image', models.ImageField(default='farm_image/default.jpg', upload_to=Api.models.upload_farm_iamge, verbose_name='FarmImage')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_name', models.CharField(default='', max_length=50)),
                ('production_image_address', models.ImageField(default='production_image/default.jpg', upload_to=Api.models.upload_production_iamge, verbose_name='ProductionImage')),
                ('production_period', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_humidity', models.FloatField()),
                ('air_humidity', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('record_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WateringHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('watering_start_time', models.DateTimeField()),
                ('watering_end_time', models.DateTimeField()),
                ('watering_crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_for_crop', to='Api.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_location_index', models.IntegerField()),
                ('area_length', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('area_width', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('field_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_farm', to='Api.farm')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops_of_field', to='Api.field'),
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_of_crop', to='Api.production'),
        ),
    ]
