# Generated by Django 3.2.3 on 2021-06-17 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='farm_mode',
            new_name='farm_auto_mode',
        ),
    ]
