# Generated by Django 3.2.3 on 2021-05-21 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops_of_field', to='Api.field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_farm', to='Api.farm'),
        ),
    ]
