# Generated by Django 3.2.3 on 2021-05-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='harvested',
            field=models.BooleanField(default=False),
        ),
    ]
