# Generated by Django 3.2.3 on 2021-06-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='data_relay_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='is_relay_on',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
