# Generated by Django 3.2.3 on 2021-05-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210521_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_harvest_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='record_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='wateringhistory',
            name='watering_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='wateringhistory',
            name='watering_start_time',
            field=models.DateTimeField(),
        ),
    ]
