# Generated by Django 3.2.3 on 2021-05-28 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_field_field_location_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iodevice',
            old_name='sensor_field',
            new_name='device_field',
        ),
        migrations.RenameField(
            model_name='iodevice',
            old_name='type',
            new_name='device_type',
        ),
    ]
