# Generated by Django 3.2.3 on 2021-05-19 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_crop_harvested'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_farm',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='farm_of_field', to='Api.farm'),
            preserve_default=False,
        ),
    ]
