# Generated by Django 3.2.3 on 2021-06-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_rename_farm_mode_farm_farm_auto_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
