# Generated by Django 3.2.3 on 2021-05-22 08:14

import Api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20210521_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_image',
            field=models.ImageField(default='farm_image/default.jpg', upload_to=Api.models.upload_to, verbose_name='Image'),
        ),
    ]
