# Generated by Django 3.2.3 on 2021-05-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_field_field_location_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='is_harvested',
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_state',
            field=models.CharField(default='hydrated', max_length=10),
            preserve_default=False,
        ),
    ]
