# Generated by Django 3.2.3 on 2021-05-28 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20210528_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='data_from_fround_sensor',
            new_name='data_from_ground_sensor',
        ),
    ]
