# Generated by Django 3.2.3 on 2021-05-26 22:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20210526_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='farm_create_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wateringhistory',
            name='Watering_field',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='water_for_field', to='Api.field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='area_length',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='field',
            name='area_width',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='field',
            name='field_location_index',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='wateringhistory',
            name='watering_crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_for_crop', to='Api.crop'),
        ),
    ]
