# Generated by Django 3.2.3 on 2021-05-26 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_alter_farm_farm_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
