# Generated by Django 3.2.3 on 2021-05-26 23:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_alter_farm_farm_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_create_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
