# Generated by Django 3.2.3 on 2021-05-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_field_field_create_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='sensordata',
            name='data_crop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_of_crop', to='Api.crop'),
        ),
        migrations.AddField(
            model_name='sensordata',
            name='data_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_of_field', to='Api.field'),
            preserve_default=False,
        ),
    ]
