# Generated by Django 3.2.3 on 2021-06-03 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_wateringhistory_water_pump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wateringhistory',
            name='water_amount',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
