# Generated by Django 3.2.3 on 2021-05-27 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0011_auto_20210528_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='air_sensor',
            name='sensor_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='air_sensor_of_field', to='Api.field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ground_sensor',
            name='sensor_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ground_sensor_of_field', to='Api.field'),
            preserve_default=False,
        ),
    ]
