# Generated by Django 3.2.3 on 2021-06-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iodevice',
            name='device_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_of_field', to='Api.field'),
        ),
    ]
