# Generated by Django 3.2.3 on 2021-05-27 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_auto_20210528_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='wateringhistory',
            name='water_pump',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='water_of_pump', to='Api.pump'),
            preserve_default=False,
        ),
    ]
