# Generated by Django 3.2.3 on 2021-05-27 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_wateringhistory_water_pump'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='pump_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pump_of_field', to='Api.field'),
            preserve_default=False,
        ),
    ]
