# Generated by Django 3.2.3 on 2021-06-05 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0014_remove_iodevice_device_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='iodevice',
            name='device_field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='device_of_field', to='Api.field'),
            preserve_default=False,
        ),
    ]
