# Generated by Django 3.2.3 on 2021-06-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0015_iodevice_device_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='crop_harvest_date',
            field=models.DateTimeField(null=True),
        ),
    ]
