# Generated by Django 3.2.3 on 2021-06-17 17:15

import Api.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_start_date', models.DateTimeField(default=datetime.datetime.now)),
                ('crop_harvest_date', models.DateTimeField(null=True)),
                ('crop_state', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(default='', max_length=50)),
                ('farm_image', models.ImageField(default='farm_image/default.jpg', upload_to=Api.models.upload_farm_iamge, verbose_name='FarmImage')),
                ('farm_create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('farm_mode', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_username', models.CharField(max_length=100)),
                ('feed_key', models.CharField(max_length=100)),
                ('feed_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_of_farm', to='Api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_location_index', models.IntegerField()),
                ('area_length', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('area_width', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('field_create_at', models.DateTimeField(default=datetime.datetime.now)),
                ('field_farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields_of_farm', to='Api.farm')),
            ],
        ),
        migrations.CreateModel(
            name='IODevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_feed_name', models.CharField(max_length=50)),
                ('device_type', models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)])),
                ('is_my_device', models.BooleanField(default=True)),
                ('device_feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_of_device', to='Api.feed')),
                ('device_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_of_field', to='Api.field')),
            ],
        ),
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_name', models.CharField(default='', max_length=50)),
                ('production_image', models.ImageField(default='production_image/default.jpg', upload_to=Api.models.upload_production_iamge, verbose_name='ProductionImage')),
                ('production_period', models.IntegerField(default=0)),
                ('production_air_temp_lower_bound', models.FloatField()),
                ('production_air_temp_upper_bound', models.FloatField()),
                ('production_soil_humid_lower_bound', models.FloatField()),
                ('production_soil_humid_upper_bound', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WateringHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_amount', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('watering_start_time', models.DateTimeField(default=datetime.datetime.now)),
                ('watering_end_time', models.DateTimeField(null=True)),
                ('water_pump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_of_pump', to='Api.iodevice')),
                ('watering_crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_for_crop', to='Api.crop')),
                ('watering_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_for_field', to='Api.field')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_humidity', models.FloatField(null=True)),
                ('air_humidity', models.FloatField(null=True)),
                ('air_temperature', models.FloatField(null=True)),
                ('is_relay_on', models.BooleanField(null=True)),
                ('record_time', models.DateTimeField(default=datetime.datetime.now)),
                ('data_ground_id', models.CharField(max_length=30, null=True)),
                ('data_air_id', models.CharField(max_length=30, null=True)),
                ('data_relay_id', models.CharField(max_length=30, null=True)),
                ('data_crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_of_crop', to='Api.crop')),
                ('data_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_of_field', to='Api.field')),
            ],
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops_of_field', to='Api.field'),
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_of_crop', to='Api.production'),
        ),
    ]
