# Generated by Django 3.2.3 on 2021-06-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_auto_20210602_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='field_stat',
            field=models.BooleanField(default=True),
        ),
    ]
