# Generated by Django 3.2.3 on 2021-06-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_field_field_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='field_stat',
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_state',
            field=models.IntegerField(default=0),
        ),
    ]
