# Generated by Django 3.2.3 on 2021-06-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20210603_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='data_from_air_sensor',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='data_from_ground_sensor',
        ),
    ]
