# Generated by Django 3.2.3 on 2021-06-02 21:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_auto_20210603_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='record_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
