# Generated by Django 3.2.3 on 2021-06-02 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_sensordata_record_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='data_from_air_sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='air_sensor', to='Api.iodevice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='data_from_ground_sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ground_sensor', to='Api.iodevice'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensordata',
            name='data_from_relay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relay', to='Api.iodevice'),
            preserve_default=False,
        ),
    ]
