# Generated by Django 3.2.3 on 2021-06-03 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0008_alter_crop_crop_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wateringhistory',
            old_name='Watering_field',
            new_name='watering_field',
        ),
        migrations.AlterField(
            model_name='wateringhistory',
            name='watering_end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='wateringhistory',
            name='watering_start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
