# Generated by Django 3.2.3 on 2021-06-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0013_alter_iodevice_device_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iodevice',
            name='device_field',
        ),
    ]
