# Generated by Django 3.2.3 on 2021-07-17 16:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('harvest_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(choices=[('HYDRATED', 'Hydrated'), ('DEHYDRATED', 'Dehydrated'), ('HARVESTED', 'Harvested')], default='HYDRATED', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('_updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('location_index', models.IntegerField()),
                ('area_length', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('area_width', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_farm', to='farm.farm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('sensor_type', models.CharField(choices=[('SOIL', 'Soil'), ('AIR', 'Air'), ('RELAY', 'Relay')], default='SOIL', max_length=32)),
                ('is_test', models.BooleanField(default=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_feed', to='farm.feed')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_field', to='field.field')),
            ],
            options={
                'db_table': 'Sensor',
            },
        ),
        migrations.CreateModel(
            name='Irrigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('end_at', models.DateTimeField(null=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_crop', to='field.crop')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_for_field', to='field.field')),
            ],
            options={
                'db_table': 'Irrigation',
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_humidity', models.FloatField(null=True)),
                ('air_humidity', models.FloatField(null=True)),
                ('air_temperature', models.FloatField(null=True)),
                ('relay', models.BooleanField(null=True)),
                ('data_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_of_crop', to='field.crop')),
                ('data_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_of_field', to='field.field')),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_field', to='field.field'),
        ),
        migrations.AddField(
            model_name='crop',
            name='production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_production', to='product.production'),
        ),
    ]
