# Generated by Django 3.2.3 on 2021-07-29 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_auto_20210728_0242'),
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='data_crop',
        ),
        migrations.RemoveField(
            model_name='data',
            name='data_field',
        ),
        migrations.AddField(
            model_name='data',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_crop', to='field.crop'),
        ),
        migrations.AddField(
            model_name='data',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='data_field', to='field.field'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='field',
            name='location_index',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('location_index', 'farm')},
        ),
    ]
