# Generated by Django 3.2.3 on 2021-07-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_auto_20210729_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='relay',
            field=models.BooleanField(default=False),
        ),
    ]
