# Generated by Django 3.2.3 on 2021-08-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_alter_data_relay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='area_length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='area_width',
            new_name='width',
        ),
        migrations.AlterField(
            model_name='field',
            name='location_index',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
