# Generated by Django 3.2.3 on 2021-08-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0004_auto_20210801_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='field',
            old_name='_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='field',
            old_name='_updated_at',
            new_name='updated_at',
        ),
    ]
