# Generated by Django 3.2.3 on 2021-08-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0005_auto_20210801_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='harvest_date',
            new_name='harvested_at',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='start_date',
            new_name='started_at',
        ),
    ]
