# Generated by Django 3.2.3 on 2021-07-17 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_farm_owner',
        ),
    ]
