# Generated by Django 3.2.3 on 2021-07-17 16:30

from django.db import migrations, models
import django.db.models.deletion
import farm.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('_updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='farm_image/default.jpg', upload_to=farm.models.upload_farm_iamge, verbose_name='farm_image')),
                ('farm_auto_mode', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'farm',
            },
        ),
        migrations.CreateModel(
            name='UserFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True)),
                ('_created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('_updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('WORKER', 'Worker')], default='OWNER', max_length=32)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_farm_farm', to='farm.farm', to_field='uuid')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_farm_user', to='user.userprofile', to_field='uuid')),
            ],
            options={
                'db_table': 'user_farm',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('key', models.CharField(max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_farm', to='farm.farm')),
            ],
        ),
    ]
