# Generated by Django 3.2.3 on 2021-07-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_is_farm_owner'),
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfarm',
            unique_together={('user', 'farm')},
        ),
    ]
