# Generated by Django 3.2.3 on 2021-07-17 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_alter_userfarm_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='farm',
        ),
    ]
