# Generated by Django 3.2.3 on 2021-07-17 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_remove_feed_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='farm',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='feed_farm', to='farm.farm', to_field='uuid'),
            preserve_default=False,
        ),
    ]
