# Generated by Django 3.2.3 on 2021-08-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_auto_20210728_0242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='_updated_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='userfarm',
            old_name='_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userfarm',
            old_name='_updated_at',
            new_name='updated_at',
        ),
    ]
