# Generated by Django 3.2.3 on 2021-08-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_auto_20210801_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='farm_auto_mode',
            new_name='auto_mode',
        ),
    ]
