# Generated by Django 3.2.3 on 2021-07-24 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='humid_upper_bound',
            new_name='soil_humid_upper_bound',
        ),
    ]
