# Generated by Django 3.2.3 on 2021-08-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_humid_upper_bound_production_soil_humid_upper_bound'),
    ]

    operations = [
        migrations.RenameField(
            model_name='production',
            old_name='_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='production',
            old_name='_updated_at',
            new_name='updated_at',
        ),
    ]
